server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tongji_follow_up?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: Tjjzkzw512!
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.rwe.tongji_follow_up.mapper: debug

rbac:
  host: www.rayplus.top:90
  scheme: https
  project-id: 6