server:
  port: 40589

spring:
  datasource:
    url: jdbc:mysql://172.16.15.2:3306/tongji_follow_up?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.rwe.tongji_follow_up.mapper: debug

rbac:
  host: 127.0.0.1:40581
  scheme: http
  project-id: 7