// /*
//  * @Descripttion: Do not edit
//  * @Author: linkenzone
//  * @Date: 2021-01-22 19:57:08
//  * 已弃用
//  */
// export const exportDataList = {
//   normal: [
//     {
//       label: '基本信息(Patient)',
//       name: 'Patient',
//       options: [
//         { label: '姓名', value: 'patientName' },
//         { label: '年龄', value: 'age' },
//         { label: '研究中心', value: 'researchCenter' },
//         { label: '身份证号', value: 'idNumber' },
//         { label: '住院号/就诊号', value: 'hospitalNumber' },
//         { label: '编号', value: 'patNumber' },
//         { label: '性别', value: 'gender' },
//         { label: '出生日期', value: 'birthday' },
//         { label: '电话号码', value: 'phoneNumber1' },
//         { label: '电话号码（选填）', value: 'phoneNumber2' },
//       ],
//     },

//     {
//       label: '既往史(PastHis)',
//       name: 'PastHis',
//       options: [
//         { label: '基础疾病史', value: 'basDisHis' },
//         { label: '传染病史', value: 'infDisHis' },

//         { label: '是否有肿瘤史', value: 'tumor' },
//         { label: '肿瘤史', value: 'tumHis' },

//         { label: '是否有肿瘤家族史', value: 'tumorFam' },
//         { label: '肿瘤家族史', value: 'tumFamHis' },

//         { label: '是否有吸烟史', value: 'smoke' },
//         { label: '吸烟史', value: 'smokingHis' },

//         { label: '是否有饮酒史', value: 'drink' },
//         { label: '饮酒史', value: 'drinkingHis' },

//         { label: '是否长期使用激素治疗', value: 'hormone' },
//         { label: '长期使用激素治疗', value: 'hormoneUseHis' },

//         { label: '是否长期使用其他药物', value: 'drug' },
//         { label: '长期使用其他药物', value: 'drugUseHis' },
//       ],
//     },

//     {
//       label: '初诊过程(IniDiaPro)',
//       name: 'IniDiaPro',
//       options: [
//         { label: '首诊PS评分', value: 'PSScore' },
//         { label: '临床表现', value: 'cliniManifest' },
//         { label: '影像学', value: 'videography' },
//         { label: '部位', value: 'part' },
//         { label: '活检方式', value: 'bioMet' },
//         { label: '是否胸膜侵犯', value: 'pleInv' },

//         { label: '标本部位', value: 'speSite' },
//         { label: '初诊日期', value: 'firVisDate' },
//         { label: '病理报告日期', value: 'patReDate' },

//         { label: '病理号', value: 'patNum' },
//         { label: '病理诊断', value: 'patDia' },
//         { label: '核分裂像/2mm2=个人显微镜8.3个40倍高倍视野', value: 'mitIma' },
//         { label: '复合性癌(记录非小细胞癌的类型)', value: 'comCar' },
//         { label: '坏死面积(占肿瘤面积的百分比)', value: 'necArea' },
//         { label: '肿块大小(mm)', value: 'massSize' },

//         // { label: 'Ki67', value: 'Ki67' },
//         { label: '转移部位', value: 'traSite' },
//         { label: 'TSize', value: 'TSize' },

//         { label: '分期情况', value: 'stage' },
//         { label: 'C分期(T,N,M)', value: 'cStage' },
//         { label: 'C临床分期', value: 'cliStage' },
//         { label: 'P分期(T,N,M)', value: 'pStage' },
//         { label: 'P临床分期', value: 'patStage' },
//         { label: 'C备注', value: 'cRemark' },
//         { label: 'P备注', value: 'pRemark' },
//       ],
//     },

//     {
//       label: '免疫组化(Immunohis)',
//       name: 'Immunohis',
//       options: [
//         { label: 'ALKD5F3', value: 'ALKD5F3' },
//         { label: 'ALKD5F3N', value: 'ALKD5F3N' },
//         { label: 'CAIX', value: 'CAIX' },
//         { label: 'CAM52', value: 'CAM52' },
//         { label: 'CD10', value: 'CD10' },
//         { label: 'CD34', value: 'CD34' },
//         { label: 'CD56', value: 'CD56' },
//         { label: 'CD117', value: 'CD117' },
//         { label: 'CDX2', value: 'CDX2' },
//         { label: 'CEA', value: 'CEA' },
//         { label: 'CgA', value: 'CgA' },
//         { label: 'CK', value: 'CK' },
//         { label: 'CK56', value: 'CK56' },
//         { label: 'CK7', value: 'CK7' },
//         { label: 'CK818', value: 'CK818' },
//         { label: 'CK19', value: 'CK19' },
//         { label: 'CK20', value: 'CK20' },
//         { label: 'Cyn', value: 'Cyn' },
//         { label: 'DLL3', value: 'DLL3' },
//         { label: 'EMA', value: 'EMA' },
//         { label: 'ERCC1', value: 'ERCC1' },
//         { label: 'LCA', value: 'LCA' },
//         { label: 'MCM2', value: 'MCM2' },
//         { label: 'NapsinA', value: 'NapsinA' },
//         { label: 'P16', value: 'P16' },
//         { label: 'P40', value: 'P40' },
//         { label: 'p53', value: 'p53' },
//         { label: 'P63', value: 'P63' },
//         { label: 'PAX2', value: 'PAX2' },
//         { label: 'PAX8', value: 'PAX8' },
//         { label: 'PCK', value: 'PCK' },
//         { label: 'PDL1', value: 'PDL1' },
//         { label: 'RRM1', value: 'RRM1' },
//         { label: 'SATB2', value: 'SATB2' },
//         { label: 'Syn', value: 'Syn' },
//         { label: 'TTF1', value: 'TTF1' },
//         { label: 'VEGFC', value: 'VEGFC' },
//         { label: 'Villin', value: 'Villin' },
//         { label: 'Villinco', value: 'Villinco' },
//         { label: 'CD516', value: 'CD516' },
//         { label: '其他', value: 'other' },
//         { label: 'Ki67', value: 'Ki67' },
//       ],
//     },

//     {
//       label: '分子检测(MoleDetec)',
//       name: 'MoleDetec',
//       options: [
//         { label: 'EGFR', value: 'EGFR' },
//         { label: 'ALK', value: 'ALK' },
//         { label: 'ROS1', value: 'ROS1' },
//         { label: 'HER_2', value: 'HER_2' },
//         { label: 'BRAF', value: 'BRAF' },
//         { label: 'cMET', value: 'cMET' },
//         { label: 'RET', value: 'RET' },
//         { label: 'NTRK', value: 'NTRK' },
//         { label: 'KRAS', value: 'KRAS' },
//         { label: 'BIM', value: 'BIM' },
//         { label: 'PIK3CA', value: 'PIK3CA' },
//         { label: 'UGT1A1', value: 'UGT1A1' },
//         { label: 'MSI', value: 'MSI' },
//         { label: 'PD-1表达', value: 'PD1' },
//         { label: 'PD1KT', value: 'PD1KT' },
//         { label: 'PD-L1表达', value: 'PDL1' },
//         { label: 'PDL1KT', value: 'PDL1KT' },
//         { label: 'TMB', value: 'TMB' },
//         { label: '其他', value: 'other' },
//       ],
//     },
//   ],

//   labExam: [
//     {
//       label: '血常规(BloodRoutine)',
//       name: 'BloodRoutine',
//       options: [
//         { label: '血常规检查时间', value: 'samplingTime' },
//         { label: 'RBC', value: 'RBC' },
//         { label: 'HGb', value: 'HGb' },
//         { label: 'HCT', value: 'HCT' },
//         { label: 'MCV', value: 'MCV' },
//         { label: 'MCH', value: 'MCH' },
//         { label: 'MCHC', value: 'MCHC' },
//         { label: 'RDWCV', value: 'RDWCV' },
//         { label: 'RDWSD', value: 'RDWSD' },
//         { label: 'WBC', value: 'WBC' },
//         { label: 'GRAN#', value: 'GRAN_' },
//         { label: 'LYM#', value: 'LYM_' },
//         { label: 'EOS#', value: 'EOS_' },
//         { label: 'MID#', value: 'MID_' },
//         { label: 'BASO#', value: 'BASO_' },
//         { label: 'PLT', value: 'PLT' },
//         { label: 'LYM', value: 'LYM' },
//         { label: 'MID', value: 'MID' },
//         { label: 'GRAN', value: 'GRAN' },
//         { label: 'EOS', value: 'EOS' },
//         { label: 'BASO', value: 'BASO' },
//         { label: 'NEUT', value: 'NEUT' },
//       ],
//     },

//     {
//       label: '血生化(BloodBio)',
//       name: 'BloodBio',
//       options: [
//         { label: '血生化检查时间', value: 'samplingTime' },
//         { label: 'TP', value: 'TP' },
//         { label: 'ALB', value: 'ALB' },
//         { label: 'GLO', value: 'GLO' },
//         { label: 'ALT', value: 'ALT' },
//         { label: 'AST', value: 'AST' },
//         { label: 'LDH', value: 'LDH' },
//         { label: 'GGT', value: 'GGT' },
//         { label: 'TBIL', value: 'TBIL' },
//         { label: 'DBIL', value: 'DBIL' },
//         { label: 'IBIL', value: 'IBIL' },
//         { label: 'GLU', value: 'GLU' },
//         { label: 'TC', value: 'TC' },
//         { label: 'LDL', value: 'LDL' },
//         { label: 'HDL', value: 'HDL' },
//         { label: 'TG', value: 'TG' },
//         { label: 'UREA', value: 'UREA' },
//         { label: 'ALP', value: 'ALP' },
//         { label: 'CREA', value: 'CREA' },
//         { label: 'UA', value: 'UA' },
//         { label: 'CO2', value: 'CO2' },
//         { label: 'K', value: 'K' },
//         { label: 'Na', value: 'Na' },
//         { label: 'Cl', value: 'Cl' },
//         { label: 'Ca', value: 'Ca' },
//         { label: 'Mg', value: 'Mg' },
//         { label: 'P', value: 'P' },
//       ],
//     },

//     {
//       label: '甲状腺功能(Thyroid)',
//       name: 'Thyroid',
//       options: [
//         { label: '甲状腺功能检查时间', value: 'samplingTime' },
//         { label: 'FT3', value: 'FT3' },
//         { label: 'FT4', value: 'FT4' },
//         { label: 'TSH', value: 'TSH' },
//       ],
//     },

//     {
//       label: '凝血功能(Coagulation)',
//       name: 'Coagulation',
//       options: [
//         { label: '凝血功能检查时间', value: 'samplingTime' },
//         { label: 'PT', value: 'PT' },
//         { label: 'APTT', value: 'APTT' },
//         { label: 'TT', value: 'TT' },
//         { label: 'FIB', value: 'FIB' },
//         { label: 'INR', value: 'INR' },
//         { label: 'D-dimer', value: 'D_dimer' },
//       ],
//     },

//     {
//       label: '心肌酶谱(MyocardialEnzyme)',
//       name: 'MyocardialEnzyme',
//       options: [
//         { label: '心肌酶谱检查时间', value: 'samplingTime' },
//         { label: 'LDH', value: 'LDH' },
//         { label: 'CK', value: 'CK' },
//         { label: 'CK-MB', value: 'CK_MB' },
//         { label: 'cTnI', value: 'cTnI' },
//         { label: 'cTnT', value: 'cTnT' },
//         { label: 'MYO', value: 'MYO' },
//         { label: 'BNP', value: 'BNP' },
//         { label: 'NT-proBNP', value: 'NT_proBNP' },
//       ],
//     },

//     {
//       label: '细胞因子(Cytokines)',
//       name: 'Cytokines',
//       options: [
//         { label: '细胞因子检查时间', value: 'samplingTime' },
//         { label: 'TNF-alpha', value: 'TNF_a' },
//         { label: 'IL-1beta', value: 'IL_1b' },
//         { label: 'IL-2R', value: 'IL_2R' },
//         { label: 'IL-6', value: 'IL_6' },
//         { label: 'IL-8', value: 'IL_8' },
//         { label: 'IL-10', value: 'IL_10' },
//       ],
//     },

//     {
//       label: '淋巴细胞亚群(LymSubsets)',
//       name: 'LymSubsets',
//       options: [
//         { label: '淋巴细胞亚群检查时间', value: 'samplingTime' },
//         { label: 'CD19#', value: 'CD19_' },
//         { label: 'CD3#', value: 'CD3_' },
//         { label: 'CD4#', value: 'CD4_' },
//         { label: 'CD8#', value: 'CD8_' },
//         { label: 'CD1656', value: 'CD16_56' },
//         { label: 'LYMPH###', value: 'LYMPH_' },
//         { label: 'CD19', value: 'CD19' },
//         { label: 'CD3', value: 'CD3' },
//         { label: 'CD4', value: 'CD4' },
//         { label: 'CD8', value: 'CD8' },
//         { label: 'CD4/CD8', value: 'CD4CD8' },
//         { label: 'CD56', value: 'CD56' },
//         { label: 'CD3CD8#', value: 'CD3_CD8__' },
//         { label: 'CD3CD8', value: 'CD3_CD8_' },
//         { label: 'CD3CD4#', value: 'CD3_CD4__' },
//         { label: 'CD3CD4', value: 'CD3_CD4_' },
//         { label: 'CD3-CD(1656)#', value: 'CD3_CD16_56_' },
//         { label: 'CD3-CD(1656)', value: 'CD3_CD16_56' },
//         { label: 'CD3-CD19#', value: 'CD3_CD19__' },
//         { label: 'CD3-CD19', value: 'CD3_CD19_' },
//         { label: 'CD8CD28', value: 'CD8_CD28_' },
//         { label: 'CD20', value: 'CD20_' },
//         { label: 'HLA-DR', value: 'HLA_DR_' },
//         { label: 'CD3/HLA-DR', value: 'CD3_HLA_DR1' },
//         { label: 'CD3/HLA-DR-', value: 'CD3_HLA_DR2' },
//         { label: 'CD3-/HLA-DR', value: 'CD3_HLA_DR3' },
//         { label: 'CD4CD25CD127low', value: 'CD4_CD25_CD127low' },
//       ],
//     },

//     {
//       label: '尿常规(UrineRoutine)',
//       name: 'UrineRoutine',
//       options: [
//         { label: '尿常规检查时间', value: 'samplingTime' },
//         { label: 'UPH', value: 'UPH' },
//         { label: 'UGLU', value: 'UGLU' },
//         { label: 'LEU', value: 'LEU' },
//         { label: 'ERY', value: 'ERY' },
//         { label: 'NIT', value: 'NIT' },
//         { label: 'BIL', value: 'BIL' },
//         { label: 'USG', value: 'USG' },
//         { label: 'KET', value: 'KET' },
//         { label: 'BLD', value: 'BLD' },
//         { label: 'PRO', value: 'PRO' },
//         { label: 'UBG', value: 'UBG' },
//         { label: 'COL', value: 'COL' },
//         { label: 'CLA', value: 'CLA' },
//       ],
//     },

//     {
//       label: '肿瘤标志物(TumorMarker)',
//       name: 'TumorMarker',
//       options: [
//         { label: '肿瘤标志物', value: 'samplingTime' },
//         { label: 'CEA', value: 'CEA' },
//         { label: 'NSE', value: 'NSE' },
//         { label: 'pro-GPR', value: 'pro_GPR' },
//         { label: 'CYFRA', value: 'CYFRA' },
//         { label: 'FERR', value: 'FERR' },
//         { label: 'AFP', value: 'AFP' },
//         { label: 'SCCA', value: 'SCCA' },
//       ],
//     },
//   ],

//   otherExam: [
//     {
//       label: '肺功能(Lung)',
//       name: 'Lung',
//       options: [
//         { label: '肺功能检查时间', value: 'detectTime' },
//         { label: '用力肺活量', value: 'FVC' },
//         { label: '用力呼气一秒率	', value: 'FEV1_FVC' },
//         { label: '用力呼气中期流速', value: 'MEF' },
//         { label: '25%用力呼气流速', value: 'MEF25' },
//         { label: '50%用力呼气流速', value: 'MEF50' },
//         { label: '75%用力呼气流速', value: 'MEF75' },
//         { label: '肺总量', value: 'TLC_sb' },
//         { label: '残气容积', value: 'RV_' },
//         { label: '残气容积/肺总量比', value: 'RV_TLC_' },
//         { label: '肺活量', value: 'VC' },
//         { label: '无需屏气弥散', value: 'DLCO_ex' },
//         { label: '肺一氧化碳弥散量', value: 'DLCO_sb' },
//         { label: '比弥散量', value: 'KCO' },
//       ],
//     },

//     {
//       label: '其他检查(OtherExams)',
//       name: 'OtherExams',
//       options: [
//         { label: '12导联心电图检测时间', value: 'ECGDetTime' },
//         { label: '12导联心电图结果描述', value: 'ECGDesc' },
//         { label: '超声心动图检测时间', value: 'UCGDetTime' },
//         { label: '超声心动图结果描述', value: 'UCGDesc' },
//       ],
//     },

//     {
//       label: '影像学检查(ImageExams)',
//       name: 'ImageExams',
//       options: [
//         { label: '影像学检查检测时间', value: 'detectTime' },
//         { label: '检查部位', value: 'examArea' },
//         { label: '检查方法', value: 'exmaMethod' },
//         { label: '肿瘤长径', value: 'tumorLD' },
//         { label: '肿瘤短径', value: 'tumorSD' },
//         { label: '肿瘤描述', value: 'tumorDesc' },
//       ],
//     },
//   ],

//   treRecord: [
//     {
//       label: '治疗记录(TreRec)',
//       name: 'TreRec',
//       options: [
//         { label: '几线治疗', value: 'trement' },
//         { label: '最佳疗效评估日期', value: 'beEffEvaDate' },
//         { label: '最佳疗效评估', value: 'beEffEva' },
//         { label: '进展日期', value: 'proDate' },
//         { label: '进展描述', value: 'proDes' },
//         { label: 'PFS/DFS', value: 'PFS_DFS' },
//       ],
//     },

//     {
//       label: '1线到5线的治疗方案(OneToFive)',
//       name: 'OneToFive',
//       options: [
//         { label: '是否加入临床治疗', value: 'isTre' },
//         { label: '临床实验名称', value: 'clinTri' },
//         { label: '治疗方案', value: 'treSolu' },
//         { label: '备注', value: 'note' },
//         { label: '开始日期', value: 'begDate' },
//         { label: '结束日期', value: 'endDate' },
//         { label: '是否重复活检', value: 'isRepBio' },
//         { label: '活检方式', value: 'bioMet' },
//         { label: '取材部位', value: 'matPart' },
//         { label: '标本库流水号', value: 'specNum' },
//         { label: '病理诊断', value: 'patDia' },
//       ],
//     },

//     {
//       label: '手术治疗(Surgery)',
//       name: 'Surgery',
//       options: [
//         { label: '手术范围', value: 'surSco' },
//         { label: '淋巴清扫范围', value: 'lymDis' },
//         { label: '清扫组数', value: 'cleGro' },
//         { label: '手术日期', value: 'surDate' },
//         { label: '术后辅助化疗', value: 'posAdjChem' },
//         { label: '是否重复活检', value: 'isRepBio' },
//         { label: '活检方式', value: 'bioMet' },
//         { label: '取材部位', value: 'matPart' },
//         { label: '标本库流水号', value: 'specNum' },
//         { label: '病理诊断', value: 'patDia' },
//       ],
//     },
//     {
//       label: '放疗(Radiotherapy)',
//       name: 'Radiotherapy',
//       options: [
//         { label: '开始日期', value: 'begDate' },
//         { label: '结束日期', value: 'endDate' },
//         { label: '放疗部位', value: 'radSite' },
//         { label: '放疗剂量', value: 'radDose' },
//         { label: '分割次数', value: 'splTim' },
//         { label: '是否重复活检', value: 'isRepBio' },
//         { label: '活检方式', value: 'bioMet' },
//         { label: '取材部位', value: 'matPart' },
//         { label: '标本库流水号', value: 'specNum' },
//         { label: '病理诊断', value: 'patDia' },
//       ],
//     },
//     {
//       label: '症状体征(Signs)',
//       name: 'Signs',
//       options: [
//         { label: '症状名称', value: 'symName' },
//         { label: '开始日期', value: 'begDate' },
//         { label: '目前是否存在', value: 'isExe' },
//         { label: '结束日期', value: 'endDate' },
//       ],
//     },
//     {
//       label: '副反应(SideEffect)',
//       name: 'SideEffect',
//       options: [
//         { label: '症状描述', value: 'sidReaName' },
//         { label: '副反应分级', value: 'sidRecCla' },
//         { label: '开始日期', value: 'begDate' },
//         { label: '目前是否存在', value: 'isExe' },
//         { label: '结束日期', value: 'endDate' },
//       ],
//     },

//     {
//       label: '随访信息(FollowUpInfo)',
//       name: 'FollowUpInfo',
//       options: [
//         { label: '计划下次随访时间', value: 'nextFollowupTime' },
//         { label: '随访日期', value: 'date' },
//         { label: '随访方式', value: 'folMet' },
//         { label: '疗效评估', value: 'effEva' },
//         { label: '生存状态', value: 'livSta' },
//         { label: '影像类型', value: 'imaFilType' },
//         { label: '备注', value: 'remarks' },
//       ],
//     },
//   ],
// };
